version: '3.4'

services:
  frontend:
    build: ./chatbot-frontend
    ports:
      - 8082:8080
    restart: always

  backend:
    build: ./chatbot-backend
    environment:
      - FLASK_APP=main.py
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=pa
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pa
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 9000:9000
    command:
      - 'php'
      - '-S'
      - '[::]:9000'
      - '-t'
      - '/var/www/html'
    entrypoint:
      - 'entrypoint.sh'
      - 'docker-php-entrypoint'
    environment:
      ADMINER_DEFAULT_SERVER: mysql
